version: "3"

services:
  backend:
    build:
      context: ./szee_backend
      dockerfile: Dockerfile
    volumes:
      - ./szee_backend/src:/backend/src
    ports:
      - "8000:8000"

  forntend:
    build:
      context: ./szee_frontend
      dockerfile: Dockerfile
    volumes:
      - ./szee_frontend/src:/frontend/src
    ports:
      - "3000:3000"