version: "3"

services:
  backend:
    build:
      context: ./szee_backend
      dockerfile: Dockerfile
    volumes:
      - ./szee_backend/src:/backend/src
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./szee_backend/.env

  forntend:
    build:
      context: ./szee_frontend
      dockerfile: Dockerfile
    volumes:
      - ./szee_frontend/src:/frontend/src
      - /node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true