# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.18.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Run npm install'

- task: DownloadSecureFile@1
  displayName: 'Download secured .env file'
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  displayName: 'Copy secured .env file to source directory'
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: '**\.env'
    TargetFolder: $(Build.SourcesDirectory)

- script: |
    npm run build
  displayName: 'Run npm build'

- task: CopyFiles@2
  displayName: 'Copy backend files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/dist/**
      **/node_modules/**/?(*.js|*.json)
      package-lock.json
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    archiveType: 'zip'
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    archiveFile: $(Build.ArtifactStagingDirectory)/build/$(Build.BuildId).zip
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Upload backend artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    artifactName: 'szee-backend'
